<?php

/**
 * @file
 * Contains rtd_salesforce.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rtd_salesforce_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rtd_salesforce module.
    case 'help.page.rtd_salesforce':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Creates the ability to send emails by selecting a view for the content, selecting a view for the list of emails and inputting how often to send') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function rtd_salesforce_theme($existing, $type, $theme, $path) {
  return [
    'rtd_salesforce' => [
      'variables' => [
        'list_id' => NULL,
        'member_id' => NULL,
        'success_page' => NULL,
        'unsubscribed_page' => NULL,
        'error_page' => NULL,
      ],
      '#attached' => [
        'library' => [
          'rtd_salesforce/rtd-salesforce'
        ]
      ]
    ],
  ];
}
